trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: docker-creds
  - group: image-cred
  - group: github_token
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:
  - stage: Sonarqube
    displayName: SonarQube
    jobs:
      - job: Sonarqube
        steps:
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'sonarqube'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'laravel'
            cliProjectName: 'laravel'
            cliSources: '.'
        - task: SonarQubeAnalyze@7
          displayName: 'Run SonarQube Scanner'
        - task: SonarQubePublish@7
          inputs:
            pollingTimeoutSec: '300'
          displayName: 'Publish SonarQube Report'

  - stage: DockerLogin
    displayName: Docker Login
    dependsOn: Sonarqube
    jobs:
      - job: DockerLogin
        steps: 
          - script: |
              echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: 'Docker Login'

  - stage: DockerBuild
    displayName: Build Docker Image
    dependsOn: DockerLogin
    jobs:
      - job: DockerBuild
        steps:
          - script: |
              docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .
            displayName: 'DockerBuild'      

  - stage: ScanTrivy
    displayName: Scan Docker Image
    dependsOn: DockerBuild
    jobs:
      - job: ScanTrivy
        steps:
          - script: |        
              trivy image --severity HIGH,CRITICAL $(IMAGE_NAME):$(IMAGE_TAG)
            displayName: 'ScanTrivy'                  

  - stage: ImagePush
    displayName: Push Docker Image
    dependsOn: ScanTrivy
    jobs:
      - job: DockerBuildPush
        steps:
          - script: |
              docker push $(IMAGE_NAME):$(IMAGE_TAG)
            displayName: 'Push Image'                     


  - stage: CodePush
    displayName: Move to ArgoCD
    jobs:
      - job: PushToGitHub
        steps:
          - checkout: self
          - script: |
              # Print current content for debugging
              echo "Current app-deployment.yaml content:"
              cat k8s/app-deployment.yaml
              
              # Update the image tag correctly
              sed -i 's|image: krishnamoorthy1/laravel-k8s:latest|image: $(IMAGE_NAME):$(IMAGE_TAG)|' k8s/app-deployment.yaml
              
              # Print updated content to verify
              echo "Updated app-deployment.yaml content:"
              cat k8s/app-deployment.yaml
              
              # Configure Git
              git config --global user.email "amuthakrishna1988@gmail.com"
              git config --global user.name "amuthakrishna"
              
              # Clone the target repository
              git clone https://$(GITHUB_TOKEN)@github.com/amuthakrishna/argocd.git argocd
              
              # Copy your files to the target repository (copying the whole directory is correct)
              cp -r k8s argocd
              
              # Push changes to the target repository
              cd argocd
              git add .
              git commit -m "Update deployment with image tag $(IMAGE_TAG)"
              git push
            displayName: 'Push to Target Repository'
            


