trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: docker-creds
  - group: image-cred

stages:
  - stage: Sonarqube
    displayName: Sonarqube login
    jobs:
      - job: Sonarqube
        steps:
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'sonarqube'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'laravel'
            cliProjectName: 'laravel'
            cliSources: '.'
        - task: SonarQubeAnalyze@7
          displayName: 'Run SonarQube Scanner'
        - task: SonarQubePublish@7
          inputs:
            pollingTimeoutSec: '300'
          displayName: 'Publish SonarQube Report'
          
  - stage: DockerLogin
    displayName: Docker Login
    dependsOn: Sonarqube
    jobs:
      - job: DockerLogin
        steps: 
          - script: |
              echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: 'Docker Login'

  - stage: DockerBuild
    displayName: Build 
    dependsOn: DockerLogin
    jobs:
      - job: DockerBuild
        steps:
          - script: |
              echo "Building image..."
              docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .
            displayName: 'DockerBuild'      

  - stage: ScanTrivy
    displayName: ScanTrivy 
    dependsOn: DockerBuild
    jobs:
      - job: ScanTrivy
        steps:
          - script: |        
              trivy image --severity HIGH,CRITICAL $(IMAGE_NAME):$(IMAGE_TAG)
            displayName: 'ScanTrivy'                  

  - stage: ImagePush
    displayName: Image Push
    dependsOn: ScanTrivy
    jobs:
      - job: DockerBuildPush
        steps:
          - script: |
              docker push $(IMAGE_NAME):$(IMAGE_TAG)
            displayName: 'Push Image'                     

