trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: docker-creds
  - group: image-cred
  - group: github_token
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:
  - stage: Sonarqube
    displayName: SonarQube
    jobs:
      - job: Sonarqube
        steps:
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'sonarqube'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'laravel'
            cliProjectName: 'laravel'
            cliSources: '.'
        - task: SonarQubeAnalyze@7
          displayName: 'Run SonarQube Scanner'
        - task: SonarQubePublish@7
          inputs:
            pollingTimeoutSec: '300'
          displayName: 'Publish SonarQube Report'

  - stage: DockerLogin
    displayName: Docker Login
    dependsOn: Sonarqube
    jobs:
      - job: DockerLogin
        steps: 
          - script: |
              echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: 'Docker Login'

  - stage: DockerBuild
    displayName: Build Docker Image
    dependsOn: DockerLogin
    jobs:
      - job: DockerBuild
        steps:
          - script: |
              docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .
            displayName: 'DockerBuild'      

  - stage: ScanTrivy
    displayName: ScanTrivy 
    dependsOn: DockerBuild
    jobs:
      - job: ScanTrivy
        steps:
          - script: |        
              trivy image --severity HIGH,CRITICAL $(IMAGE_NAME):$(IMAGE_TAG)
            displayName: 'ScanTrivy'                  

  - stage: ImagePush
    displayName: Push Docker Image
    dependsOn: ScanTrivy
    jobs:
      - job: DockerBuildPush
        steps:
          - script: |
              docker push $(IMAGE_NAME):$(IMAGE_TAG)
            displayName: 'Push Image'                     


  - stage: CodePush
    displayName: Checkout and Push Code to Another Repo
    dependsOn: ImagePush
    jobs:
      - job: CheckoutAndPush
        steps:
          - checkout: self

          - script: |
              # Replace image tag
              sed -i 's|image: $(IMAGE_NAME):.*|image: $(IMAGE_NAME):$(IMAGE_TAG)|' k8s/app-deployment.yaml

              # Git config
              git config --global user.email "amuthakrishna1988@gmail.com"
              git config --global user.name "amuthakrishna"

              # Clean remote and re-add to avoid 'already exists' error
              git remote remove target 2>/dev/null || true
              git remote add target https://$(GITHUB_TOKEN)@github.com/amuthakrishna/lamp-ticket-cd.git

              # Fetch and pull remote using conflict-safe strategy
              git fetch target
              git checkout main
              git pull target main --strategy=recursive -X theirs --allow-unrelated-histories --no-edit || true

              # Add and commit changes
              git add k8s
              git commit -m 'Move to Live' || echo "Nothing to commit"

              # Push to target repo
              git push target main
            displayName: 'Safe Pull, Merge and Push to lamp-ticket-cd'


