persistence:
  enabled: true
  size: 5Gi
adminPassword: "admin"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    kubernetes:
      gnetId: 14205
      revision: 1
      datasource: Prometheus
    node-exporter:
      gnetId: 16098
      revision: 1
      datasource: Prometheus
service:
  type: LoadBalancer
